Adds sample app to chapter 4-setup-prometheus-stack
digitalocean/Kubernetes-Starter-Kit-Developers pull request #172
Opened 2022-07-06 08:30 UTC by v-bpastiu

Removes the ambassador example in chapter 04.
Adds the Emojivoto example and related explanations.

2022-07-07 13:39 UTC, v-ctiutiu requested changes

2022-07-18 06:07 UTC, v-bpastiu commented on 04-setup-prometheus-stack/README.md
> +5. [Kustomize](https://kubectl.docs.kubernetes.io/installation/kustomize/), for deploying a kubernetes sample app from the Kubernetes Sample Apps[Repository](https://github.com/digitalocean/kubernete
Correct. Kustomize is already covered in the emojivoto sample app.

2022-07-18 10:41 UTC, mtiutiu-heits approved these changes
Looks good to me.

2022-07-18 10:42 UTC, v-ctiutiu approved these changes
Looks good to me.

2022-07-18 10:43 UTC, merged