Refactors chapter 7
digitalocean/Kubernetes-Starter-Kit-Developers pull request #178
Opened 2022-07-25 09:45 UTC by v-bpastiu

2022-07-25 11:34 UTC, v-ctiutiu requested changes

2022-07-25 11:34 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
>  ## Table of contents
I would add a requirements or prerequisites section to this chapter as well. In it, you can refer to the Prometheus monitoring stack as the first requirement, then Emoji sample app, then Slack incoming webhook configuration, and any other requirement this chapter may have.

Don't forget to update TOC afterwards.

2022-07-25 11:34 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
> +## Configuring Alertmanager to Send Notification to Slack
Maybe:

> Configuring Alertmanager to Send Notifications to Slack

2022-07-25 11:34 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
> +Next, we will add the necessary config to `AlertManager` to enable `Slack` notifications. Open the `04-setup-prometheus-stack/assets/manifests/prom-stack-values.yaml` file provided in the `Starter Ki
Try not to use the "we".

2022-07-25 11:34 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
> +Often times we need to be notified immediately about any critical issue in our cluster. That is where `AlertManager` comes into the picture. `Alertmanager` helps in aggregating the `alerts`, and send
Try not to use the "we".

2022-07-25 11:34 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
>        slack_api_url: "https://hooks.slack.com/services/TXXXX/BXXXX/<token>"
You can use a `<YOUR_SLACK_APP_INCOMING_WEBHOOK_URL_HERE>` placeholder here.

2022-07-25 11:45 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
> +At this point, you should see the slack `notifications` for firing alerts when the expected number of pods for `Emojivoto` is less than 4.
You are giving an example for a scenario where the emojivoto application pods count is less than 4. But, I don't see how you trigger this situation. Is there a step missing where you are downscaling the application to let's say 3 pods to simulate this scenario ?

2022-07-25 12:15 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
> +    --create-namespace \
You don't need the `--create-namespace` flag in this case.

2022-07-26 08:09 UTC, v-ctiutiu requested changes

2022-07-26 08:09 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
> +- `slack_configs` - configuration related to the channel to send the notification to, the title and the message it should include.
> `receivers.[].slack_configs` - defines the Slack channel used to send notifications, notification title and the actual message. It is also possible to format the notification message (or body) based on your requirements.

2022-07-26 08:09 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
> +At this point, you should see the slack `notifications` for firing alerts when the expected number of pods for `Emojivoto` is less than 4.
Maybe:

> At this point, you should receive slack notifications for firing alerts when the expected number of pods for `Emojivoto` is less than 4.

2022-07-26 08:09 UTC, v-ctiutiu commented on 07-alerting-and-notification/README.md
> +Next, you will be testing the firing of the `Alert` and the sending of the `Slack` notification by downscaling the number of replicas for a `deployment` in the `emojivoto` namespace.
Be more concise:

> Next, you're going to test if the `EmojivotoInstanceDown` alert works by downscaling the number of replicas for the `emoji` deployment from the `emojivoto` namespace.

2022-07-26 08:12 UTC, v-bpastiu commented on 04-setup-prometheus-stack/assets/manifests/prom-stack-values-v35.5.1.yaml
>    # Starter Kit setup for DigitalOcean Block Storage
I can remove it.

2022-07-26 08:56 UTC, v-ctiutiu approved these changes
Looks good to me now.

2022-07-26 08:58 UTC, merged